/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
export const TYPERT = {
  package: 'clawock-dsh',
  face: 'client',
  schemas: [
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [],
    "objects": [
      {
        "tags": [
          {
            "name": "typert",
            "comment": "object — client face surface for the Typert generator.",
            "text": "@typert object — client face surface for the Typert generator."
          }
        ],
        "jsDoc": "/** @typert object — client face surface for the Typert generator. */",
        "name": "DecisionMindStoreShape",
        "exportName": "DecisionMindStoreShape",
        "members": [
          {
            "kind": "property",
            "name": "filter",
            "signature": "filter: string"
          },
          {
            "kind": "property",
            "name": "open",
            "signature": "open: string | null"
          },
          {
            "kind": "property",
            "name": "visibleDateCount",
            "signature": "visibleDateCount: number"
          },
          {
            "kind": "property",
            "name": "foldedDates",
            "signature": "foldedDates: string[]"
          },
          {
            "kind": "property",
            "name": "scrollTop",
            "signature": "scrollTop: number"
          }
        ],
        "types": []
      }
    ]
  },
}
