/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { LedgerResult, ListRunsResult, PlansResult, PortfolioResult, RunDetailResult, TracesResult } from 'clawock-dsh/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636c61776f636b53747564696f {
    get: (runId: string) => Promise<RemoteResult<RunDetailResult>>
    ledger: () => Promise<RemoteResult<LedgerResult>>
    list: () => Promise<RemoteResult<ListRunsResult>>
    plans: () => Promise<RemoteResult<PlansResult>>
    portfolio: () => Promise<RemoteResult<PortfolioResult>>
    traces: () => Promise<RemoteResult<TracesResult>>
  }
  interface TypertRemoteMap {
    'clawockStudio/get': (runId: string) => Promise<RemoteResult<RunDetailResult>>
    'clawockStudio/ledger': () => Promise<RemoteResult<LedgerResult>>
    'clawockStudio/list': () => Promise<RemoteResult<ListRunsResult>>
    'clawockStudio/plans': () => Promise<RemoteResult<PlansResult>>
    'clawockStudio/portfolio': () => Promise<RemoteResult<PortfolioResult>>
    'clawockStudio/traces': () => Promise<RemoteResult<TracesResult>>
  }
  interface TypertRemoteNamespaceMap {
    'clawockStudio': TypertRemoteNamespace$636c61776f636b53747564696f
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
