#!/usr/bin/env bash
# Put `clawock` on PATH for this host.
#
# The host Python is externally managed (PEP 668), so install the portable
# product and KCNyu adapter into a dedicated virtualenv. The stable launcher
# keeps every OpenClaw payload unchanged while entry-point discovery proves the
# live phase came from the separately installed instance distribution—not from
# a source-tree `scripts/harness` import.
set -euo pipefail

CHECKOUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET="${2:-$HOME/.local/bin/clawock}"
VENV="${3:-$HOME/.local/share/clawock/venv}"

[ -f "$CHECKOUT/src/clawock/cli.py" ] || { echo "not a clawock checkout: $CHECKOUT" >&2; exit 1; }
[ -f "$CHECKOUT/instances/kcnyu/pyproject.toml" ] || { echo "missing KCNyu adapter: $CHECKOUT" >&2; exit 1; }
mkdir -p "$(dirname "$TARGET")"
python3 -m venv "$VENV"
"$VENV/bin/python" -m pip install --quiet -e "$CHECKOUT[compute]" -e "$CHECKOUT/instances/kcnyu"

cat > "$TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by scripts/ops/install_clawock_launcher.sh — do not hand-edit.
# Both distributions are editable, so a git fast-forward changes behavior while
# Python metadata still exposes the adapter entry points.
exec env CLAWOCK_INSTANCE=kcnyu CLAWOCK_WORKSPACE="$CHECKOUT" \\
     "$VENV/bin/clawock" "\$@"
LAUNCHER
chmod +x "$TARGET"
echo "installed: $TARGET -> $VENV/bin/clawock (workspace $CHECKOUT)"
