#!/usr/bin/env bash
# Put `clawock` on PATH for this host.
#
# Why a launcher and not `pip install -e .`: this box runs an externally-managed
# system Python (PEP 668). Overriding that with --break-system-packages on the
# machine every cron and the money pipeline depend on trades a tidy install for
# a risk to the interpreter itself, which is a bad trade. A venv would work but
# would then have to be threaded through every cron payload AND the crontab
# watchdogs — more moving parts than the problem justifies.
#
# The engine does not need this: `clawock` is importable from the checkout and
# runs against any workspace (see tests/test_runs_against_a_foreign_book.py).
# The launcher is HOST WIRING — instance, by docs/reference/product-vs-instance.md
# — which is why it is installed by a script rather than shipped as host state
# nobody can reproduce.
set -euo pipefail

CHECKOUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET="${2:-$HOME/.local/bin/clawock}"

[ -f "$CHECKOUT/clawock/cli.py" ] || { echo "not a clawock checkout: $CHECKOUT" >&2; exit 1; }
mkdir -p "$(dirname "$TARGET")"

cat > "$TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by scripts/ops/install_clawock_launcher.sh — do not hand-edit.
# Editable by design: it points at the checkout, so a git ff changes behaviour
# with no reinstall, which is what the live box needs.
exec env PYTHONPATH="$CHECKOUT\${PYTHONPATH:+:\$PYTHONPATH}" \\
     python3 -m clawock.cli "\$@"
LAUNCHER
chmod +x "$TARGET"
echo "installed: $TARGET -> $CHECKOUT"
