"""Network/build ceilings shared by cron contracts and their postflights.

The inner retry ladders stay intact. A whole agent turn must reserve this
post-delivery chain plus time to collect data, judge and deliver the product.
"""
GIT_CALL_TIMEOUT_SECONDS = 120
PUSH_ATTEMPTS = 3
PUSH_RETRY_BACKOFF_STEP_SECONDS = 3
DEPLOY_REQUEST_TIMEOUT_SECONDS = 120
PUBLISH_NETWORK_CALLS = 2 + PUSH_ATTEMPTS
PUBLISH_BUDGET_SECONDS = (
    PUBLISH_NETWORK_CALLS * GIT_CALL_TIMEOUT_SECONDS
    + sum(attempt * PUSH_RETRY_BACKOFF_STEP_SECONDS for attempt in range(1, PUSH_ATTEMPTS))
    + DEPLOY_REQUEST_TIMEOUT_SECONDS
)
DASHBOARD_FETCH_TIMEOUT_SECONDS = 60
DASHBOARD_LOCK_WAIT_SECONDS = 90
DASHBOARD_BUILD_TIMEOUT_SECONDS = 30
DECISION_MAP_TIMEOUT_SECONDS = 180
SAFE_PUSH_ATTEMPTS = 3
PREPUSH_ATTEMPT_SECONDS = 90
PUSH_RETRY_BACKOFF_SECONDS = 9
PUSH_TIMEOUT_SECONDS = SAFE_PUSH_ATTEMPTS * PREPUSH_ATTEMPT_SECONDS + PUSH_RETRY_BACKOFF_SECONDS
POST_DELIVERY_BUDGET_SECONDS = (
    DASHBOARD_FETCH_TIMEOUT_SECONDS + DASHBOARD_LOCK_WAIT_SECONDS
    + DASHBOARD_BUILD_TIMEOUT_SECONDS + DECISION_MAP_TIMEOUT_SECONDS
    + PUBLISH_BUDGET_SECONDS + PUSH_TIMEOUT_SECONDS
)
PRE_DELIVERY_RESERVE_SECONDS = 300
