#!/usr/bin/env python3
"""Generate docs/operations/cron-schedules.md from config/cron-schedules.json."""
from __future__ import annotations

import argparse
from pathlib import Path

from cron_contract import load_contract

# The checkout root, so `clawock` resolves from the tree this file ships
# in. Reached through the scripts/data/workspace shim until #267 step 3,
# whose only remaining job was inserting this path as a side effect.
import sys  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))
from clawock.workspace import workspace_root  # noqa: E402

WS = workspace_root(Path(__file__).resolve().parents[2])
OUTPUT = WS / "docs" / "operations" / "cron-schedules.md"


def schedule_text(item: dict) -> str:
    seasonal = item.get("seasonal_schedules")
    if seasonal:
        day = seasonal["daylight"]["expr"]
        standard = seasonal["standard"]["expr"]
        return f"EDT `{day}`<br>EST `{standard}`"
    schedule = item["schedule"]
    tz = schedule.get("tz") or "host HKT"
    return f"`{schedule['expr']}` · {tz}"


def watchdog_text(job: dict) -> str:
    rendered = []
    watchdogs = []
    if "watchdog" in job:
        watchdogs.append(("primary watchdog", job["watchdog"]))

    extra_watchdogs = job.get("extra_watchdogs")
    if extra_watchdogs is None:
        pass
    elif not isinstance(extra_watchdogs, list):
        rendered.append("⚠ malformed extra_watchdogs: expected a list")
    else:
        watchdogs.extend(
            (f"extra watchdog {index}", watchdog)
            for index, watchdog in enumerate(extra_watchdogs, start=1)
        )

    for label, watchdog in watchdogs:
        if not isinstance(watchdog, dict):
            rendered.append(f"⚠ malformed {label}: expected an object")
            continue
        if "schedule" not in watchdog and not watchdog.get("seasonal_schedules"):
            rendered.append(f"⚠ malformed {label}: missing schedule")
            continue
        try:
            text = schedule_text(watchdog)
        except (AttributeError, KeyError, TypeError) as exc:
            rendered.append(f"⚠ malformed {label}: invalid schedule ({exc})")
            continue
        if purpose := watchdog.get("purpose"):
            text += f" · {purpose}"
        rendered.append(text)
    return "<br>".join(rendered) or "—"


def render(contract: dict) -> str:
    rows = []
    for job in contract["jobs"]:
        rows.append(
            f"| {job['name']} | {schedule_text(job)} | {job.get('mode', '—')} | "
            f"`{job.get('harness', '—')}` | {watchdog_text(job)} |"
        )
    return "\n".join([
        "# Cron schedule contract / 调度契约",
        "",
        "<!-- GENERATED by scripts/data/generate_cron_docs.py; DO NOT EDIT. -->",
        "",
        "This file is the generated human view of `config/cron-schedules.json`. Runtime truth",
        "is `openclaw cron list --json`; `ops/system_check.py` checks runtime schedules,",
        "payload semantics, watchdog crontab lines, and the daily DST synchronizer against",
        "the contract before every push.",
        "",
        "本文由 `config/cron-schedules.json` 自动生成。运行态以 `openclaw cron list --json`",
        "为准；每次 push 前，system check 会同时校验 schedule、payload 语义、watchdog 和 DST",
        "同步任务。禁止手改本表；修改 contract 后运行生成器。",
        "",
        "## DST policy / 夏令时策略",
        "",
        "US market jobs remain expressed in HKT because the daemon's ET timezone parser has",
        "regressed before. `sync_us_cron_dst.py --apply` runs daily at **06:20 HKT**, derives",
        "the season from `America/New_York`, and updates both OpenClaw jobs and their system",
        "watchdogs. The overnight monitor always stops at 02:30 HKT so 03:00 memory dreaming",
        "keeps an exclusive window; standard time therefore has two fewer US intraday slots.",
        "",
        "美股 job 继续使用 HKT 表达式，但由每日 06:20 的同步器按纽约真实 UTC offset 自动",
        "切换。隔夜盯盘无论冬夏令时都在 02:30 HKT 截止，保留 03:00 dreaming 独占窗口；",
        "因此冬令时比夏令时少两个盘中 slot。",
        "",
        "## OpenClaw jobs + watchdogs",
        "",
        "| Job | OpenClaw schedule | Mode | Harness | System watchdog |",
        "|---|---|---|---|---|",
        *rows,
        "",
        "## Operational invariants / 运维不变量",
        "",
        "- Exactly 11 enabled OpenClaw jobs; 10 market jobs plus memory promotion.",
        "- Six report, three intraday, and two brief watchdog passes are tracked; the brief",
        "  uses an 08:30 delivery backstop plus a 09:05 post-window miss detector.",
        "- Market payloads use deterministic preflight/postflight, `delivery.mode=none`,",
        "  a unique WeChat path, Telegram mirror, and an ordered unique subset of the",
        "  fixed model candidates defined by the contract. Runtime rotations must remain",
        "  a prefix of that order; health checks never reorder or skip candidates.",
        "- Mode 7 writes the public `assets/data/cron-heartbeats.json` ledger through the",
        "  existing single publisher; cron health verifies every monitored slot.",
        "- Mode 7 agent turns run on every scheduled slot. The pre-model delta trigger",
        "  was removed on 2026-07-27: model workload is not the binding constraint, and",
        "  a silently skipped slot is indistinguishable from a dead cron. Closed markets",
        "  are still handled downstream by the preflight/postflight calendar gate.",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(load_contract())
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print("docs/operations/cron-schedules.md is stale; run generate_cron_docs.py")
            return 1
        print("docs/operations/cron-schedules.md matches contract")
        return 0
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
