/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
export const TYPERT = {
  package: 'clawock-dsh',
  face: 'client',
  schemas: [
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "One session committed a different agent preset to its durable log. Consumers invalidate only state derived from that session's composition.",
        "summary": "One session committed a different agent preset to its durable log.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit\n         *"
          },
          {
            "name": "param",
            "argument": "sessionId",
            "comment": "- the session whose composition changed.",
            "text": "@param sessionId - the session whose composition changed.\n         *"
          },
          {
            "name": "param",
            "argument": "agentPreset",
            "comment": "- the preset recorded by the committed selection.",
            "text": "@param agentPreset - the preset recorded by the committed selection."
          }
        ],
        "jsDoc": "/**\n * One session committed a different agent preset to its durable log.\n * Consumers invalidate only state derived from that session's composition.\n * @mode emit\n * @param sessionId - the session whose composition changed.\n * @param agentPreset - the preset recorded by the committed selection.\n */",
        "name": "agent-preset/selected",
        "mode": "emit",
        "signature": "'agent-preset/selected'(sessionId: SessionId, agentPreset: string): void"
      },
      {
        "description": "A command was registered or unregistered. This is an unfiltered registry notification because a global or scoped change may affect any UI view. Observer failures are contained and cannot veto the registry mutation.",
        "summary": "A command was registered or unregistered.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A command was registered or unregistered. This is an unfiltered registry\n * notification because a global or scoped change may affect any UI view.\n * Observer failures are contained and cannot veto the registry mutation.\n * @mode emit\n */",
        "name": "commands/change",
        "mode": "emit",
        "signature": "'commands/change'(): void"
      },
      {
        "description": "A connection generation was (re-)established. Wire-derived caches must treat their state as stale and repull (commands directory; the queue mirrors reset themselves through the session resync path).",
        "summary": "A connection generation was (re-)established.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A connection generation was (re-)established. Wire-derived caches must\n * treat their state as stale and repull (commands directory; the queue\n * mirrors reset themselves through the session resync path).\n * @mode emit\n */",
        "name": "connection/reset",
        "mode": "emit",
        "signature": "'connection/reset'(): void"
      },
      {
        "description": "One exact Plugin/Package activation is now live in the Host.",
        "summary": "One exact Plugin/Package activation is now live in the Host.",
        "tags": [
          {
            "name": "param",
            "argument": "pkg",
            "comment": "- stable plugin, immutable package, run identity, and label.",
            "text": "@param pkg - stable plugin, immutable package, run identity, and label.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One exact Plugin/Package activation is now live in the Host.\n * @param pkg - stable plugin, immutable package, run identity, and label.\n * @mode emit\n */",
        "name": "cordis/dynamic-package",
        "mode": "emit",
        "signature": "'cordis/dynamic-package'(pkg: DynamicCordisPackage): void"
      },
      {
        "description": "One exact activation was withdrawn.",
        "summary": "One exact activation was withdrawn.",
        "tags": [
          {
            "name": "param",
            "argument": "retracted",
            "comment": "- plugin, package, and run identity.",
            "text": "@param retracted - plugin, package, and run identity.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One exact activation was withdrawn.\n * @param retracted - plugin, package, and run identity.\n * @mode emit\n */",
        "name": "cordis/dynamic-retract",
        "mode": "emit",
        "signature": "'cordis/dynamic-retract'(retracted: DynamicCordisRetracted): void"
      },
      {
        "description": "Request a live read-only query from the Client inspect registry.",
        "summary": "Request a live read-only query from the Client inspect registry.",
        "tags": [
          {
            "name": "param",
            "argument": "request",
            "comment": "- correlation, Session, provider, method, and JSON input.",
            "text": "@param request - correlation, Session, provider, method, and JSON input.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Request a live read-only query from the Client inspect registry.\n * @param request - correlation, Session, provider, method, and JSON input.\n * @mode emit\n */",
        "name": "cordis/inspect-query",
        "mode": "emit",
        "signature": "'cordis/inspect-query'(request: CordisInspectQueryRequest): void"
      },
      {
        "description": "Notify every Client that an inspect query has settled or been cancelled.",
        "summary": "Notify every Client that an inspect query has settled or been cancelled.",
        "tags": [
          {
            "name": "param",
            "argument": "resolved",
            "comment": "- exact query identity that is no longer answerable.",
            "text": "@param resolved - exact query identity that is no longer answerable.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Notify every Client that an inspect query has settled or been cancelled.\n * @param resolved - exact query identity that is no longer answerable.\n * @mode emit\n */",
        "name": "cordis/inspect-query-resolved",
        "mode": "emit",
        "signature": "'cordis/inspect-query-resolved'(resolved: CordisInspectQueryResolved): void"
      },
      {
        "description": "A Client-bearing activation needs a browser page, and may require a user decision.",
        "summary": "A Client-bearing activation needs a browser page, and may require a user decision.",
        "tags": [
          {
            "name": "param",
            "argument": "request",
            "comment": "- correlation identity, owner, target version, mode, and approval requirement.",
            "text": "@param request - correlation identity, owner, target version, mode, and approval requirement.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A Client-bearing activation needs a browser page, and may require a user decision.\n * @param request - correlation identity, owner, target version, mode, and approval requirement.\n * @mode emit\n */",
        "name": "cordis/request-run",
        "mode": "emit",
        "signature": "'cordis/request-run'(request: DynamicCordisRunRequest): void"
      },
      {
        "description": "A pending Client activation request left the answerable state.",
        "summary": "A pending Client activation request left the answerable state.",
        "tags": [
          {
            "name": "param",
            "argument": "resolved",
            "comment": "- request identity and outcome.",
            "text": "@param resolved - request identity and outcome.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A pending Client activation request left the answerable state.\n * @param resolved - request identity and outcome.\n * @mode emit\n */",
        "name": "cordis/request-run-resolved",
        "mode": "emit",
        "signature": "'cordis/request-run-resolved'(resolved: DynamicCordisRequestResolved): void"
      },
      {
        "description": "Committed change to a provider-managed credential source: a `set`, an `unset`, or an external edit observed in storage. Ambient process-environment changes are not observable and never emit. Listener failures are contained and logged — a sync throw and an async rejection alike — without changing the committed operation's outcome, except `INVARIANT`-coded failures, which rethrow after every listener ran; that rethrow reaches the emitter only from synchronous listeners, so invariant checks on this event must not be async functions.",
        "summary": "Committed change to a provider-managed credential source: a `set`, an `unset`, or an external edit observed in storage.",
        "tags": [
          {
            "name": "param",
            "argument": "ref",
            "comment": "- the reference whose stored value changed.",
            "text": "@param ref - the reference whose stored value changed.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Committed change to a provider-managed credential source: a `set`, an\n * `unset`, or an external edit observed in storage. Ambient\n * process-environment changes are not observable and never emit. Listener\n * failures are contained and logged — a sync throw and an async rejection\n * alike — without changing the committed operation's outcome, except\n * `INVARIANT`-coded failures, which rethrow after every listener ran;\n * that rethrow reaches the emitter only from synchronous listeners, so\n * invariant checks on this event must not be async functions.\n * @param ref - the reference whose stored value changed.\n * @mode emit\n */",
        "name": "credentials/updated",
        "mode": "emit",
        "signature": "'credentials/updated'(ref: CredentialRef): void"
      },
      {
        "description": "The provider topology changed: an adapter registered or unregistered routes, or the configurable-provider directory gained or lost entries. This payload-free registry notification fires at each commit point (including registration disposal); consumers re-read `listProviders()`, `listModels()`, or `listConfigurableProviders()` for the new state. Observer failures are contained and cannot veto the registry mutation.",
        "summary": "The provider topology changed: an adapter registered or unregistered routes, or the configurable-provider directory gained or lost entries.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * The provider topology changed: an adapter registered or unregistered\n * routes, or the configurable-provider directory gained or lost entries.\n * This payload-free registry notification fires at each commit point\n * (including registration disposal); consumers re-read `listProviders()`,\n * `listModels()`, or `listConfigurableProviders()` for the new state.\n * Observer failures are contained and cannot veto the registry mutation.\n * @mode emit\n */",
        "name": "llm/adapters-updated",
        "mode": "emit",
        "signature": "'llm/adapters-updated'(): void"
      },
      {
        "description": "Waterfall around every streaming model call (retry, replay, routing). Bound to the {@link LlmRuntime}; call `next()` to reach the resolved adapter's stream, or yield your own chunks to short-circuit.",
        "summary": "Waterfall around every streaming model call (retry, replay, routing).",
        "tags": [
          {
            "name": "param",
            "argument": "options",
            "comment": "- the full request. A LOOP-built request carries the process-local {@link markAgentLoopRequest} identity and arrives deep-frozen (mutation throws): its content is a pure function of the session log (the reconstructability Agent Note), so listeners read it, never rewrite it. Hand-built calls do not carry that marker; their messages already obey the immutable creation contract.",
            "text": "@param options - the full request. A LOOP-built request carries the\n         *   process-local {@link markAgentLoopRequest} identity and arrives deep-frozen\n         *   (mutation throws): its content is a pure function of the session log (the\n         *   reconstructability Agent Note), so listeners read it, never rewrite it.\n         *   Hand-built calls do not carry that marker; their messages already obey\n         *   the immutable creation contract.\n         *"
          },
          {
            "name": "mode",
            "comment": "waterfall",
            "text": "@mode waterfall"
          }
        ],
        "jsDoc": "/**\n * Waterfall around every streaming model call (retry, replay, routing).\n * Bound to the {@link LlmRuntime}; call `next()` to reach the resolved\n * adapter's stream, or yield your own chunks to short-circuit.\n * @param options - the full request. A LOOP-built request carries the\n *   process-local {@link markAgentLoopRequest} identity and arrives deep-frozen\n *   (mutation throws): its content is a pure function of the session log (the\n *   reconstructability Agent Note), so listeners read it, never rewrite it.\n *   Hand-built calls do not carry that marker; their messages already obey\n *   the immutable creation contract.\n * @mode waterfall\n */",
        "name": "llm/stream",
        "mode": "waterfall",
        "signature": "'llm/stream'(this: LlmRuntime, options: GenerateOptions, next: () => AsyncIterable<StreamChunk>): AsyncIterable<StreamChunk>"
      },
      {
        "description": "One registered namespace's RAW user section changed, whether or not the resolved value did. `settings/updated` is the consumer-facing event and stays deep-equal-gated; this one exists for configuration surfaces, which must learn that a field went from inherited to overridden (same resolved value, different meaning) and that their held revision is stale. Listener containment matches `settings/updated`.",
        "summary": "One registered namespace's RAW user section changed, whether or not the resolved value did.",
        "tags": [
          {
            "name": "param",
            "argument": "ns",
            "comment": "- the namespace whose stored section changed.",
            "text": "@param ns - the namespace whose stored section changed.\n         *"
          },
          {
            "name": "param",
            "argument": "revision",
            "comment": "- the namespace's new revision.",
            "text": "@param revision - the namespace's new revision.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One registered namespace's RAW user section changed, whether or not the\n * resolved value did. `settings/updated` is the consumer-facing event and\n * stays deep-equal-gated; this one exists for configuration surfaces,\n * which must learn that a field went from inherited to overridden (same\n * resolved value, different meaning) and that their held revision is\n * stale. Listener containment matches `settings/updated`.\n * @param ns - the namespace whose stored section changed.\n * @param revision - the namespace's new revision.\n * @mode emit\n */",
        "name": "settings/document-updated",
        "mode": "emit",
        "signature": "'settings/document-updated'(ns: SettingsNamespace, revision: number): void"
      },
      {
        "description": "Committed change to one registered namespace's resolved value. Emitted after the provider persisted (for `update`) or published (`provider`) the change; never emitted when the resolved value is deep-equal. Listener failures are contained and logged — a sync throw and an async rejection alike — except `INVARIANT`-coded failures, which rethrow after every listener ran; that rethrow reaches the emitter only from synchronous listeners, so invariant checks on this event must not be async functions.",
        "summary": "Committed change to one registered namespace's resolved value.",
        "tags": [
          {
            "name": "param",
            "argument": "ns",
            "comment": "- the namespace whose resolved value changed.",
            "text": "@param ns - the namespace whose resolved value changed.\n         *"
          },
          {
            "name": "param",
            "argument": "next",
            "comment": "- the new resolved value.",
            "text": "@param next - the new resolved value.\n         *"
          },
          {
            "name": "param",
            "argument": "prev",
            "comment": "- the previous resolved value.",
            "text": "@param prev - the previous resolved value.\n         *"
          },
          {
            "name": "param",
            "argument": "source",
            "comment": "- whether the change entered through `update()` or the provider.",
            "text": "@param source - whether the change entered through `update()` or the provider.\n         *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Committed change to one registered namespace's resolved value. Emitted\n * after the provider persisted (for `update`) or published (`provider`)\n * the change; never emitted when the resolved value is deep-equal.\n * Listener failures are contained and logged — a sync throw and an async\n * rejection alike — except `INVARIANT`-coded failures, which rethrow\n * after every listener ran; that rethrow reaches the emitter only from\n * synchronous listeners, so invariant checks on this event must not be\n * async functions.\n * @param ns - the namespace whose resolved value changed.\n * @param next - the new resolved value.\n * @param prev - the previous resolved value.\n * @param source - whether the change entered through `update()` or the provider.\n * @mode emit\n */",
        "name": "settings/updated",
        "mode": "emit",
        "signature": "'settings/updated'(ns: SettingsNamespace, next: unknown, prev: unknown, source: SettingsUpdateSource): void"
      },
      {
        "description": "A slot's definition or registration set changed.",
        "summary": "A slot's definition or registration set changed.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit\n         *"
          },
          {
            "name": "param",
            "argument": "key",
            "comment": "- the mutated SlotMap key.",
            "text": "@param key - the mutated SlotMap key."
          }
        ],
        "jsDoc": "/**\n * A slot's definition or registration set changed.\n * @mode emit\n * @param key - the mutated SlotMap key.\n */",
        "name": "slots/changed",
        "mode": "emit",
        "signature": "'slots/changed'(key: string): void"
      }
    ],
    "objects": []
  },
}
