/**
 * clawock-dsh build:runs the official Typert generator inside a temporary
 * Harness-shaped workspace, because the rc.6 `@deepseek-ai/dsh-typert-generator`
 * only recognizes the `@Remote` decorator when `@deepseek-ai/dsh-typert-protocol`
 * is a sibling workspace package (the Harness monorepo layout; see
 * dsh-notebook's documented workaround and dsh-workspace-plugin's build.mjs).
 *
 * Emits the Host reflection (lib/typert.host.*) and the client Remote
 * contribution (lib/typert.remote-client.*), compiles the browser client
 * bundle, and wraps it as a `window.__ModuleLoader__.load({...})` closure.
 * Generated `lib/` artifacts are committed — CI and DSH consume them without
 * a build step (same practice as dsh-notebook).
 */

import { cp, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { execFile } from 'node:child_process'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'

const exec = promisify(execFile)
const repo = process.cwd()

function json(value) { return `${JSON.stringify(value, null, 2)}\n` }
async function writeJson(file, value) {
  await mkdir(dirname(file), { recursive: true })
  await writeFile(file, json(value))
}

async function wrapWebClient(file) {
  let source = (await readFile(file, 'utf8')).replace(/[ \t]+$/gm, '')
  // The bundler stamps each `//#region` with the module's path *as resolved on
  // this machine*, so building the same source in a different directory
  // produced a different committed artifact (17 lines of pure path churn when
  // the same commit was built from another worktree). The generated lib/ is
  // committed and reviewed, so it has to be a function of the source alone —
  // otherwise "does lib/ match a build of src/?" is unanswerable. Normalize
  // the path to the package-relative one it should have been.
  source = source.replace(
    /^(\/\/#(?:end)?region )(.*?)(node_modules\/.*)$/gm,
    (_, tag, _abs, rest) => `${tag}${rest}`,
  )
  const match = source.match(/export \{ ([^}]+) \};\n?$/)
  if (!match) throw new Error('client bundle must end with named exports')
  const exports = match[1]
  let body = source.slice(0, match.index)
  body = body.replace(/^import \{ ([^}]+) \} from ["']([^"']+)["'];?$/gm, (_, names, id) => `const { ${names} } = require("${id}");`)
  body = body.replace(/^import \* as ([A-Za-z_$][\w$]*) from ["']([^"']+)["'];?$/gm, (_, name, id) => `const ${name} = require("${id}");`)
  body = body.replace(/^import ([A-Za-z_$][\w$]*) from ["']([^"']+)["'];?$/gm, (_, name, id) => `const ${name} = require("${id}").default ?? require("${id}");`)
  body = body.replace(/^import ["']([^"']+)["'];?$/gm, (_, id) => `require("${id}");`)
  if (/^\s*(?:import|export)\b/m.test(body)) throw new Error('client bundle must be self-contained')
  await writeFile(file, `window.__ModuleLoader__.load({
  id: "clawock-dsh",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${body}
    Object.assign(exports, { ${exports} });
    return module.exports;
  }
});
`)
}

const root = await mkdtemp(join(tmpdir(), 'clawock-dsh-build-'))
try {
  const plugin = join(root, 'packages/clawock-dsh')
  const protocol = join(root, 'packages/protocol')
  await symlink(join(repo, 'node_modules'), join(root, 'node_modules'), 'junction')
  await writeJson(join(root, 'package.json'), { name: 'clawock-dsh-build', private: true, type: 'module' })
  await mkdir(plugin, { recursive: true })
  await cp(join(repo, 'src'), join(plugin, 'src'), { recursive: true })
  // Placeholder Remote contribution; regenerated by the Host face pass below.
  await writeFile(join(plugin, 'src/typert.remote-client.js'), "export const TYPERT_REMOTE = { package: 'clawock-dsh', descriptors: [] }\n")
  await writeFile(join(plugin, 'src/typert.remote-client.d.ts'), "export declare const TYPERT_REMOTE: import('@deepseek-ai/dsh-typert-protocol').TypertRemoteContribution\n")
  await cp(join(repo, 'package.json'), join(plugin, 'package.json'))
  await cp(join(repo, 'cordis.patch.yml'), join(plugin, 'cordis.patch.yml'))
  await cp(join(repo, 'node_modules/@deepseek-ai/dsh-typert-protocol/lib'), join(protocol, 'lib'), { recursive: true })
  await writeJson(join(protocol, 'package.json'), {
    name: '@deepseek-ai/dsh-typert-protocol', private: true, type: 'module',
    exports: { '.': { types: './lib/types/index.d.ts', default: './lib/index.js' }, './types': { types: './lib/types/types.d.ts', default: './lib/types/types.js' } },
  })
  await writeJson(join(protocol, 'tsconfig.json'), { extends: '../../tsconfig.base.json', compilerOptions: { rootDir: 'lib', outDir: 'lib/types', noEmit: true }, files: ['lib/types/index.d.ts', 'lib/types/types.d.ts'] })
  await writeJson(join(root, 'tsconfig.base.json'), {
    compilerOptions: {
      target: 'ES2024', module: 'ESNext', moduleResolution: 'Bundler', strict: true, composite: true,
      noEmit: true, allowImportingTsExtensions: true, skipLibCheck: true, types: ['node'],
      paths: {
        '@deepseek-ai/dsh-typert-protocol': ['./packages/protocol/lib/types/index.d.ts'],
        '@deepseek-ai/dsh-typert-protocol/types': ['./packages/protocol/lib/types/types.d.ts'],
        'clawock-dsh': ['./packages/clawock-dsh/src/index.ts'],
        'clawock-dsh/client': ['./packages/clawock-dsh/src/client.ts'],
        'clawock-dsh/types': ['./packages/clawock-dsh/src/types.ts'],
        'clawock-dsh/*': ['./packages/clawock-dsh/src/*'],
      },
    },
  })
  await writeJson(join(plugin, 'tsconfig.json'), { extends: '../../tsconfig.base.json', compilerOptions: { rootDir: 'src', outDir: 'lib/types', noEmit: true }, include: ['src'] })
  await writeJson(join(root, 'tsconfig.host.json'), { extends: './tsconfig.base.json', files: [], references: [{ path: './packages/protocol' }, { path: './packages/clawock-dsh' }] })
  await writeJson(join(root, 'tsconfig.client.json'), { extends: './tsconfig.base.json', files: [], references: [{ path: './packages/protocol' }, { path: './packages/clawock-dsh' }] })
  await writeJson(join(root, 'tsconfig.bundle.json'), { compilerOptions: { target: 'ES2024', module: 'ESNext', moduleResolution: 'Bundler', strict: true, allowImportingTsExtensions: true, skipLibCheck: true, types: ['node'] } })
  await writeJson(join(root, 'tsconfig.declarations.json'), { extends: './tsconfig.base.json', compilerOptions: { rootDir: 'packages/clawock-dsh/src', outDir: 'packages/clawock-dsh/lib/types', declaration: true, emitDeclarationOnly: true, noEmit: false }, include: ['packages/clawock-dsh/src'] })
  await writeFile(join(root, 'tsdown.host.config.mjs'), `import { defineConfig } from 'tsdown'
import { typertPlugin } from '@deepseek-ai/dsh-typert-generator/tsdown'
export default defineConfig({ entry: {
  index: 'packages/clawock-dsh/src/index.ts',
  scan: 'packages/clawock-dsh/src/scan.ts',
  ledger: 'packages/clawock-dsh/src/ledger.ts',
  freshness: 'packages/clawock-dsh/src/freshness.ts',
}, outDir: 'packages/clawock-dsh/lib', format: ['esm'], platform: 'node', target: 'es2024', fixedExtension: false, dts: false, clean: false, external: [/^@deepseek-ai\\//], plugins: [typertPlugin({ mode: 'workspace', faces: ['host', 'client'] })] })
`)
  await writeFile(join(root, 'tsdown.client.config.mjs'), `import { defineConfig } from 'tsdown'
export default defineConfig({ entry: { client: 'packages/clawock-dsh/src/client.ts' }, outDir: 'packages/clawock-dsh/lib', format: ['esm'], platform: 'browser', target: 'es2024', fixedExtension: false, dts: false, clean: false, outputOptions: { codeSplitting: false }, external: ['react', 'react/jsx-runtime', 'react/jsx-dev-runtime', /^@deepseek-ai\\//], deps: { alwaysBundle: ['zod'] } })
`)
  const node = process.execPath
  const tsdown = join(repo, 'node_modules/tsdown/dist/run.mjs')
  const tsc = join(repo, 'node_modules/typescript/bin/tsc')
  const run = (args) => exec(node, [tsdown, ...args], { cwd: root, stdio: 'inherit' })
  await run(['--config', 'tsdown.host.config.mjs', '--tsconfig', 'tsconfig.bundle.json', '--no-report'])
  await cp(join(plugin, 'lib/typert.remote-client.js'), join(plugin, 'src/typert.remote-client.js'))
  await run(['--config', 'tsdown.client.config.mjs', '--tsconfig', 'tsconfig.bundle.json', '--no-report'])
  await run([tsc, '-p', 'tsconfig.declarations.json', '--pretty', 'false'])
  await rm(join(plugin, 'lib/typert.remote-client.d.ts.map'), { force: true })
  await rm(join(repo, 'lib'), { recursive: true, force: true })
  await cp(join(plugin, 'lib'), join(repo, 'lib'), { recursive: true })
  await wrapWebClient(join(repo, 'lib/client.js'))
  console.log('built clawock-dsh/lib')
} finally {
  await rm(root, { recursive: true, force: true })
}
