#!/usr/bin/env bash
# Put `clawock` on PATH for this host.
#
# The host Python is externally managed (PEP 668), so install the portable
# product and KCNyu adapter into a dedicated virtualenv. The stable launcher
# keeps every OpenClaw payload unchanged while entry-point discovery proves the
# live phase came from the separately installed instance distribution—not from
# a source-tree import.
set -euo pipefail

CHECKOUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET="${2:-$HOME/.local/bin/clawock}"
VENV="${3:-$HOME/.local/share/clawock/venv}"
TARGET_DIR="$(dirname "$TARGET")"

[ -f "$CHECKOUT/src/clawock/cli.py" ] || { echo "not a clawock checkout: $CHECKOUT" >&2; exit 1; }
[ -f "$CHECKOUT/instances/kcnyu/pyproject.toml" ] || { echo "missing KCNyu adapter: $CHECKOUT" >&2; exit 1; }
mkdir -p "$TARGET_DIR"
python3 -m venv "$VENV"
"$VENV/bin/python" -m pip install --quiet -e "${CHECKOUT}[compute]" -e "$CHECKOUT/instances/kcnyu"

cat > "$TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by ops/host/install_clawock_launcher.sh — do not hand-edit.
# Both distributions are editable, so a git fast-forward changes behavior while
# Python metadata still exposes the adapter entry points.
#
# Defaults, not overrides. A bare "env VAR=x" wins over the caller's environment,
# which silently defeated CLAWOCK_WORKSPACE: pointing the installed command at
# another book ran it against this desk live ledger instead, and wrote to it.
# (No backticks in this heredoc: it is unquoted, so they would be executed.)
exec env CLAWOCK_INSTANCE="\${CLAWOCK_INSTANCE:-kcnyu}" \\
     CLAWOCK_WORKSPACE="\${CLAWOCK_WORKSPACE:-$CHECKOUT}" \\
     "$VENV/bin/clawock" "\$@"
LAUNCHER
chmod +x "$TARGET"

for COMMAND in \
  clawock-kcnyu-brief-watchdog \
  clawock-kcnyu-report-watchdog \
  clawock-kcnyu-intraday-watchdog \
  clawock-kcnyu-cron-heartbeat \
  clawock-kcnyu-workflow-outcomes \
  clawock-kcnyu-intraday-delta \
  clawock-kcnyu-gold-fetch \
  clawock-kcnyu-gold-update \
  clawock-kcnyu-influencer-scan \
  clawock-kcnyu-brief-fallback \
  clawock-kcnyu-news-digest \
  clawock-kcnyu-weekly-review
do
  [ -x "$VENV/bin/$COMMAND" ] || { echo "missing installed command: $VENV/bin/$COMMAND" >&2; exit 1; }
  COMMAND_TARGET="$TARGET_DIR/$COMMAND"
  cat > "$COMMAND_TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by ops/host/install_clawock_launcher.sh — do not hand-edit.
exec env CLAWOCK_INSTANCE="\${CLAWOCK_INSTANCE:-kcnyu}" \
     CLAWOCK_WORKSPACE="\${CLAWOCK_WORKSPACE:-$CHECKOUT}" \
     "$VENV/bin/$COMMAND" "\$@"
LAUNCHER
  chmod +x "$COMMAND_TARGET"
done

echo "installed: clawock + 12 KCNyu runtime commands in $TARGET_DIR (workspace $CHECKOUT)"
