#!/usr/bin/env bash
# Put `clawock` on PATH for this host.
#
# The host Python is externally managed (PEP 668), so install clawock into a
# dedicated virtualenv. Profiles select desk values; all executable behavior is
# supplied by this one distribution.
set -euo pipefail

CHECKOUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET="${2:-$HOME/.local/bin/clawock}"
VENV="${3:-$HOME/.local/share/clawock/venv}"
TARGET_DIR="$(dirname "$TARGET")"

[ -f "$CHECKOUT/src/clawock/cli.py" ] || { echo "not a clawock checkout: $CHECKOUT" >&2; exit 1; }
mkdir -p "$TARGET_DIR"
python3 -m venv "$VENV"
"$VENV/bin/python" -m pip install --quiet -e "${CHECKOUT}[market]"

cat > "$TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by ops/host/install_clawock_launcher.sh — do not hand-edit.
# The distribution is editable, so a git fast-forward changes implementation.
#
# Defaults, not overrides. A bare "env VAR=x" wins over the caller's environment,
# which silently defeated CLAWOCK_WORKSPACE: pointing the installed command at
# another book ran it against this desk live ledger instead, and wrote to it.
# (No backticks in this heredoc: it is unquoted, so they would be executed.)
exec env CLAWOCK_PROFILE="\${CLAWOCK_PROFILE:-kcnyu}" \\
     CLAWOCK_WORKSPACE="\${CLAWOCK_WORKSPACE:-$CHECKOUT}" \\
     "$VENV/bin/clawock" "\$@"
LAUNCHER
chmod +x "$TARGET"

for COMMAND in \
  clawock-brief-watchdog \
  clawock-report-watchdog \
  clawock-intraday-watchdog \
  clawock-cron-heartbeat \
  clawock-workflow-outcomes \
  clawock-intraday-delta \
  clawock-gold-fetch \
  clawock-gold-update \
  clawock-influencer-scan \
  clawock-brief-fallback \
  clawock-news-digest \
  clawock-weekly-review
do
  [ -x "$VENV/bin/$COMMAND" ] || { echo "missing installed command: $VENV/bin/$COMMAND" >&2; exit 1; }
  COMMAND_TARGET="$TARGET_DIR/$COMMAND"
  cat > "$COMMAND_TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by ops/host/install_clawock_launcher.sh — do not hand-edit.
exec env CLAWOCK_PROFILE="\${CLAWOCK_PROFILE:-kcnyu}" \
     CLAWOCK_WORKSPACE="\${CLAWOCK_WORKSPACE:-$CHECKOUT}" \
     "$VENV/bin/$COMMAND" "\$@"
LAUNCHER
  chmod +x "$COMMAND_TARGET"
done

echo "installed: clawock + 12 runtime commands in $TARGET_DIR (workspace $CHECKOUT)"
